name: 'Sample String Action'
description: 'Sample github action with ts'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  repo-token:
    description: 'Github token'
    required: true
  milliseconds:
    description: 'Your input description here'
    required: true

runs:
  using: node20
  main: dist/index.js
